# ----------------------- #
# Site
# ----------------------- #

title: NodeJS Portable
author: Gareth Flowers

# ----------------------- #
# Jekyll
# ----------------------- #

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-sitemap
